name: run-all

on:
  schedule:
    - cron: '37 9 * * *'
  workflow_dispatch:

jobs:

  URL:
    uses: ./.github/workflows/URL.yml

  shorts:
    needs: URL
    uses: ./.github/workflows/shorts.yml

  videos:
    needs: shorts
    uses: ./.github/workflows/videos.yml
