name: Run All

on:
  schedule:
    - cron: '37 9 * * *'
  workflow_dispatch:

jobs:

  url_shorts:
    uses: ./.github/workflows/url_shorts.yml

  shorts:
    needs: url_shorts
    uses: ./.github/workflows/shorts.yml

  videos:
    needs: shorts
    uses: ./.github/workflows/videos.yml
