name: Run All

on:
  schedule:
    - cron: '37 9 * * *'
  workflow_dispatch:

jobs:
  url_shorts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # setup java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run URL Shorts
        #run: mvn exec:java -Dexec.mainClass="yt.UrlShorts"
        run: mvn -e -X exec:java -Dexec.mainClass="yt.MidDayTest"
        
      - name: Run Shorts
        run: mvn exec:java -Dexec.mainClass="yt.ytShorts"

      - name: Run Videos
        run: mvn exec:java -Dexec.mainClass="yt.ytVideos"
