name: Daily Shorts Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test
        run: echo "Workflow working"
