name: Shorts Automation

on:
  workflow_dispatch:

  schedule:
    - cron: '15 9 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Maven
        run: mvn -version

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core

      - name: Install Playwright Browsers
        run: |
          mvn exec:java \
          -Dexec.mainClass=com.microsoft.playwright.CLI \
          -Dexec.args="install"

      - name: Build Project
        run: mvn clean compile

      - name: Run Shorts Automation
        run: |
          mvn exec:java \
          -Dexec.mainClass="yt.ytShorts"
