name: URL_Shorts

on:
  workflow_dispatch:

  schedule:
    - cron: '11 16 * * *'

permissions:
  contents: write

jobs:
  update-urls:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Playwright Browsers
        run: |
          mvn exec:java \
          -Dexec.mainClass=com.microsoft.playwright.CLI \
          -Dexec.args="install"

      - name: Build Project
        run: mvn clean compile

      - name: Run URL Scraper
        run: |
          mvn exec:java \
          -Dexec.mainClass="yt.MidDayTest"

      - name: Commit Updated urls.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add urls.txt

          git diff --cached --quiet || git commit -m "Auto updated urls.txt"

          git push

